import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import { Providers } from './providers';
import { Container } from '@chakra-ui/react';

const inter = Kanit({ subsets: ['thai'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Container pt={4} maxW='container.2xl'>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
